### ISSUE TITLE
owncloud full build ( collabora, onlyoffice) with keycloak.

### ISSUE THREAD

**Issue by arsalaaan** [owncloud/docs-ocis#1039]
**Hi there,**
Can someone please help me build ocis_full (collabora, onlyoffice etc) with ocis_keycloak. I tried alot to merge both build but owncloud keeps buffering and do not redirect to keycloak. However. when i tried to merge ocis_full into keycloak, then only office does not work.
One more issue is that I'm unable to install my own SSL into traefik.

`traefik-1   | time="2024-10-29T18:59:03Z" level=error msg="Unable to obtain ACME certificate for domains \"c.mydomain.com\": unable to generate a certificate for the domains [c.mydomain.com]: error: one or more domains had a problem:\n[c.mydomain.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 1.2.3.4: Invalid response from http://c.mydomain.com/.well-known/acme-challenge/7SJ-5dIt_kg_-n9PU4Tb_gAEHyYYBCEHnj6CyqjFmDM: 403\n" rule="Host(`c.mydomain.com`)" ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=http.acme routerName=ocis@docker
traefik-1   | time="2024-10-29T18:59:05Z" level=error msg="Unable to obtain ACME certificate for domains \"kc.mydomain.com\": unable to generate a certificate for the domains [kc.mydomain.com]: error: one or more domains had a problem:\n[kc.mydomain.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 1.2.3.4: Invalid response from http://kc.mydomain.com/.well-known/acme-challenge/G3kCJArQvmY8klpuFchZFygXd_KTZOFYJLiHs6ol4jE: 403\n" routerName=keycloak@docker rule="Host(`kc.mydomain.com`)" providerName=http.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"`

note: mydomain.com and 1.2.3.4 is just example here, I'm using actual domain, with record already published.

When I merge keycloak with collabora, wopi, onlyoffice. ( I tried to open keycloak first and proceed to unsafe as i can't install SSL but no luck)
![image](https://github.com/user-attachments/assets/61280420-1aa0-4554-831c-fea73a9851b6)

**Comment by mmattel** [comment]
@arsalaaan I would split things into two steps:

1. Follow the [admin docs](https://doc.owncloud.com/ocis/next/depl-examples/ubuntu-compose/ubuntu-compose-prod.html) for the compose setup. This works great.
2. Adapt the setting to use Keykloak.
Here, I would recommend you to ask for support in https://central.owncloud.org or https://talk.owncloud.com/channel/infinitescale 

IMPORTANT: The compose description is currently reworked, no worry. We are currently referencing rolling releases and close to a new v7 to be published soon. The changes mainly address updating and upgrading. With v7, switch docs to 7.0 and you will get updated compose files providing new web features that can be enabled.

**Comment by mmattel** [comment]
@arsalaaan great to hear that you configured Infinite Scale to work with Keycloak 😄 

Though I have not tested this, I dont have an oo-ee license at my hand, using ee should not be a big issue. In `onlyoffice.yml`, you need to change the image
from `onlyoffice/documentserver:8.2.0` to `onlyoffice/documentserver-ee:8.2.0`
Then you need to add a volume to provide your license (license.lic) file. To do so see [Registering your Enterprise Edition version](https://helpcenter.onlyoffice.com/installation/docs-enterprise-install-docker.aspx).

**Comment by arsalaaan** [comment]
Hi There,

I'm unable to use onlyoffice in ocis_full build. only collabora is working. I'm getting the following error in onlyoffice.


/var/log/onlyoffice/documentserver/docservice/err.log
[2024-11-06T19:21:15.239] [ERROR] [localhost] [7eab2cf8040e9d32eb640c0c64136c5f13677c3f8cdeb434ac6382a6e20c585a] [userId] nodeJS - wopi error LOCK:Error: Error response: statusCode:409; headers:{"content-length":"0","date":"Wed, 06 Nov 2024 19:21:15 GMT","x-collaboration.onlyoffice-version":"6.6.1","x-request-id":"329599a980b9/OIbFUaGBth-000006","x-wopi-lock":"cool-lockf93d2c27","x-wopi-lockfailurereason":"Conflicting LockID"}; body:

    at Request._callback (/snapshot/server/Common/sources/utils.js)
    at Request.callback (/snapshot/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/snapshot/server/Common/node_modules/request/request.js:1161:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/snapshot/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)


![image](https://github.com/user-attachments/assets/0117faee-ba89-44c0-bd57-ee612c7b06b0)

**Comment by anthonyrom** [comment]
@arsalaaan it looks like you're running into a WOPI file lock error- could the file you're trying to access be in use by something else? Are you running both Collabora _and_ OnlyOffice at once? You will need to use only one at a time. You can also enable the debug logs for the collaboration service which may reveal more details.

That said, you've made it further than I have with OnlyOffice+OCIS. What are you using for a WOPI server? How are your domains configured? I just get a blank pane when opening a file with OnlyOffice from OCIS, and no errors in the logs at all.

**Comment by mmattel** [comment]
I retested the example I [linked above](https://github.com/owncloud/docs-ocis/issues/1039#issuecomment-2446074816), both using 7.0 and the upcoming 7.1 release (updated ocis + updated compose images). All of them are running fine...? I highly guess that you messed up reconfiguring the example with your changes.
